# Generated by Django 5.2.14 on 2026-05-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0006_rename_status_supportticket_submission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='pending_comment',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
